version: '3'

services:
  bootstrap:
    build: .
    ports:
      - '8000:8000'
    command: ['python', 'p2pnode.py', '--bootstrap', '8000']

  node1:
    build: .
    ports:
      - '8001:8001'
    command: ['python', 'p2pnode.py', '8001', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node2:
    build: .
    ports:
      - '8002:8002'
    command: ['python', 'p2pnode.py', '8002', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node3:
    build: .
    ports:
      - '8003:8003'
    command: ['python', 'p2pnode.py', '8003', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node4:
    build: .
    ports:
      - '8004:8004'
    command: ['python', 'p2pnode.py', '8004', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node5:
    build: .
    ports:
      - '8005:8005'
    command: ['python', 'p2pnode.py', '8005', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node6:
    build: .
    ports:
      - '8006:8006'
    command: ['python', 'p2pnode.py', '8006', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node7:
    build: .
    ports:
      - '8007:8007'
    command: ['python', 'p2pnode.py', '8007', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node8:
    build: .
    ports:
      - '8008:8008'
    command: ['python', 'p2pnode.py', '8008', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node9:
    build: .
    ports:
      - '8009:8009'
    command: ['python', 'p2pnode.py', '8009', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node10:
    build: .
    ports:
      - '8010:8010'
    command: ['python', 'p2pnode.py', '8010', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node11:
    build: .
    ports:
      - '8011:8011'
    command: ['python', 'p2pnode.py', '8011', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node12:
    build: .
    ports:
      - '8012:8012'
    command: ['python', 'p2pnode.py', '8012', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node13:
    build: .
    ports:
      - '8013:8013'
    command: ['python', 'p2pnode.py', '8013', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node14:
    build: .
    ports:
      - '8014:8014'
    command: ['python', 'p2pnode.py', '8014', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node15:
    build: .
    ports:
      - '8015:8015'
    command: ['python', 'p2pnode.py', '8015', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node16:
    build: .
    ports:
      - '8016:8016'
    command: ['python', 'p2pnode.py', '8016', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node17:
    build: .
    ports:
      - '8017:8017'
    command: ['python', 'p2pnode.py', '8017', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node18:
    build: .
    ports:
      - '8018:8018'
    command: ['python', 'p2pnode.py', '8018', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node19:
    build: .
    ports:
      - '8019:8019'
    command: ['python', 'p2pnode.py', '8019', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node20:
    build: .
    ports:
      - '8020:8020'
    command: ['python', 'p2pnode.py', '8020', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node21:
    build: .
    ports:
      - '8021:8021'
    command: ['python', 'p2pnode.py', '8021', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node22:
    build: .
    ports:
      - '8022:8022'
    command: ['python', 'p2pnode.py', '8022', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node23:
    build: .
    ports:
      - '8023:8023'
    command: ['python', 'p2pnode.py', '8023', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node24:
    build: .
    ports:
      - '8024:8024'
    command: ['python', 'p2pnode.py', '8024', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node25:
    build: .
    ports:
      - '8025:8025'
    command: ['python', 'p2pnode.py', '8025', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node26:
    build: .
    ports:
      - '8026:8026'
    command: ['python', 'p2pnode.py', '8026', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node27:
    build: .
    ports:
      - '8027:8027'
    command: ['python', 'p2pnode.py', '8027', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node28:
    build: .
    ports:
      - '8028:8028'
    command: ['python', 'p2pnode.py', '8028', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node29:
    build: .
    ports:
      - '8029:8029'
    command: ['python', 'p2pnode.py', '8029', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node30:
    build: .
    ports:
      - '8030:8030'
    command: ['python', 'p2pnode.py', '8030', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node31:
    build: .
    ports:
      - '8031:8031'
    command: ['python', 'p2pnode.py', '8031', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node32:
    build: .
    ports:
      - '8032:8032'
    command: ['python', 'p2pnode.py', '8032', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node33:
    build: .
    ports:
      - '8033:8033'
    command: ['python', 'p2pnode.py', '8033', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node34:
    build: .
    ports:
      - '8034:8034'
    command: ['python', 'p2pnode.py', '8034', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node35:
    build: .
    ports:
      - '8035:8035'
    command: ['python', 'p2pnode.py', '8035', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node36:
    build: .
    ports:
      - '8036:8036'
    command: ['python', 'p2pnode.py', '8036', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node37:
    build: .
    ports:
      - '8037:8037'
    command: ['python', 'p2pnode.py', '8037', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node38:
    build: .
    ports:
      - '8038:8038'
    command: ['python', 'p2pnode.py', '8038', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node39:
    build: .
    ports:
      - '8039:8039'
    command: ['python', 'p2pnode.py', '8039', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node40:
    build: .
    ports:
      - '8040:8040'
    command: ['python', 'p2pnode.py', '8040', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node41:
    build: .
    ports:
      - '8041:8041'
    command: ['python', 'p2pnode.py', '8041', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node42:
    build: .
    ports:
      - '8042:8042'
    command: ['python', 'p2pnode.py', '8042', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node43:
    build: .
    ports:
      - '8043:8043'
    command: ['python', 'p2pnode.py', '8043', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node44:
    build: .
    ports:
      - '8044:8044'
    command: ['python', 'p2pnode.py', '8044', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node45:
    build: .
    ports:
      - '8045:8045'
    command: ['python', 'p2pnode.py', '8045', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node46:
    build: .
    ports:
      - '8046:8046'
    command: ['python', 'p2pnode.py', '8046', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node47:
    build: .
    ports:
      - '8047:8047'
    command: ['python', 'p2pnode.py', '8047', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node48:
    build: .
    ports:
      - '8048:8048'
    command: ['python', 'p2pnode.py', '8048', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node49:
    build: .
    ports:
      - '8049:8049'
    command: ['python', 'p2pnode.py', '8049', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

  node50:
    build: .
    ports:
      - '8050:8050'
    command: ['python', 'p2pnode.py', '8050', 'http://bootstrap:8000']
    volumes:
      - shared-storage:/app/storage
    depends_on:
      - bootstrap

volumes:
  shared-storage:
